org.gradle.jvmargs=-Xmx2G

# Fabric (https://fabricmc.net/versions.html)
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.1
loader_version=0.16.10

# Mod Properties
mod_version=0.1
maven_group=me.orly.dupe
archives_base_name=dupe-addon

# Dependency Versions

# Meteor (https://maven.meteordev.org/)
meteor_version=0.5.0-SNAPSHOT
